workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 90
    instance_type: mac_mini_m4
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "${BUNDLE_ID}"
        APP_NAME: "${APP_NAME}"
        SKU: "${SKU}"
        APPLE_ID: "${APPLE_ID}"
        P8_KEY_PATH: "${P8_KEY_PATH}"
        APPLE_KEY_ID: "${APPLE_KEY_ID}"
        APPLE_ISSUER_ID: "${APPLE_ISSUER_ID}"
        PRIMARY_CATEGORY: "${PRIMARY_CATEGORY}"
        SECONDARY_CATEGORY: "${SECONDARY_CATEGORY}"
        PRICE_TIER: "${PRICE_TIER}"
        SUBMIT_FOR_REVIEW: "${SUBMIT_FOR_REVIEW}"
        AUTOMATIC_RELEASE: "${AUTOMATIC_RELEASE}"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "${BUNDLE_ID}"
    cache:
      cache_paths:
        - $HOME/.codemagic_keys
        - $HOME/.gem
        - ios/vendor/bundle
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Ensure CERTIFICATE_PRIVATE_KEY
        script: |
          KEY_FILE="$HOME/.codemagic_keys/ios_dist_private_key"
          mkdir -p "$HOME/.codemagic_keys"
          if [ -f "$KEY_FILE" ]; then
            echo "Reusing cached CERTIFICATE_PRIVATE_KEY"
          else
            echo "Generating new CERTIFICATE_PRIVATE_KEY"
            ssh-keygen -t rsa -b 2048 -m PEM -f "$KEY_FILE" -q -N ""
          fi
          echo "CERTIFICATE_PRIVATE_KEY<<DELIMITER" >> $CM_ENV
          cat "$KEY_FILE" >> $CM_ENV
          echo "" >> $CM_ENV
          echo "DELIMITER" >> $CM_ENV

      - name: Set up App Store Connect API key
        script: |
          echo "APP_STORE_CONNECT_KEY_IDENTIFIER=$APPLE_KEY_ID" >> $CM_ENV
          echo "APP_STORE_CONNECT_ISSUER_ID=$APPLE_ISSUER_ID" >> $CM_ENV
          echo "APP_STORE_CONNECT_PRIVATE_KEY<<KEYDELIMITER" >> $CM_ENV
          cat "$CM_BUILD_DIR/$P8_KEY_PATH" >> $CM_ENV
          echo "" >> $CM_ENV
          echo "KEYDELIMITER" >> $CM_ENV

      - name: Set up iOS code signing
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE --create
          keychain initialize
          app-store-connect certificates list \
            --type IOS_DISTRIBUTION \
            --certificate-key=@env:CERTIFICATE_PRIVATE_KEY --save
          keychain add-certificates
          xcode-project use-profiles

      - name: Manage iOS version
        script: |
          pip3 install PyJWT cryptography requests
          VERSION_JSON=$(python3 scripts/manage_version_ios.py 2>/dev/null || echo '{"version":"1.0.0","version_id":"","state":"NEW"}')
          APP_VERSION=$(echo "$VERSION_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['version'])")
          APP_VERSION_ID=$(echo "$VERSION_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin).get('version_id',''))")
          APP_STATUS=$(echo "$VERSION_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin).get('state','NEW'))")
          echo "APP_VERSION=$APP_VERSION" >> $CM_ENV
          echo "APP_VERSION_ID=$APP_VERSION_ID" >> $CM_ENV
          echo "APP_STATUS=$APP_STATUS" >> $CM_ENV
          echo "iOS version: $APP_VERSION (state: $APP_STATUS)"

      - name: Set Flutter version
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$BUNDLE_ID" 2>/dev/null || echo "0") + 1))
          if [ -z "$APP_VERSION" ] || [ "$APP_VERSION" = "" ]; then
            APP_VERSION="1.0.0"
          fi
          sed -i '' "s/^version:.*/version: ${APP_VERSION}+${BUILD_NUMBER}/" pubspec.yaml
          echo "Building: $APP_VERSION+$BUILD_NUMBER"

      - name: Flutter packages
        script: flutter pub get

      - name: Build iOS
        script: flutter build ipa --release --export-options-plist=/tmp/export.plist

      - name: Install Fastlane
        script: |
          cd ios
          gem install bundler
          bundle install

      - name: Create app record (idempotent)
        script: |
          cd ios
          bundle exec fastlane produce create \
            -u "$APPLE_ID" \
            -a "$BUNDLE_ID" \
            --app_name "$APP_NAME" \
            --sku "$SKU" \
            || true

      - name: Deploy to App Store
        script: |
          cd ios
          bundle exec fastlane deploy_ios

      - name: Sync IAP and subscriptions
        script: |
          if ./scripts/check_changed.sh fastlane/iap_config.json; then
            cd ios
            bundle exec fastlane sync_iap
          else
            echo "IAP config unchanged - skipping"
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m4
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "${PACKAGE_NAME}"
        APP_NAME: "${APP_NAME}"
        BUNDLE_ID: "${BUNDLE_ID}"
        GOOGLE_SA_JSON_PATH: "${GOOGLE_SA_JSON_PATH}"
        KEYSTORE_PASSWORD: "${KEYSTORE_PASSWORD}"
        TRACK: "${TRACK}"
        ROLLOUT_FRACTION: "${ROLLOUT_FRACTION}"
        IN_APP_UPDATE_PRIORITY: "${IN_APP_UPDATE_PRIORITY}"
        APPLE_KEY_ID: "${APPLE_KEY_ID}"
        APPLE_ISSUER_ID: "${APPLE_ISSUER_ID}"
        P8_KEY_PATH: "${P8_KEY_PATH}"
    cache:
      cache_paths:
        - $HOME/.gem
        - $HOME/.gradle/caches
        - android/vendor/bundle
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Ensure Android upload keystore
        script: |
          KEYSTORE_PATH="$CM_BUILD_DIR/android/upload.keystore"
          if [ -f "$KEYSTORE_PATH" ]; then
            echo "Using existing upload keystore from repo"
          else
            echo "Generating new upload keystore..."
            keytool -genkey -v \
              -keystore "$KEYSTORE_PATH" \
              -storetype JKS \
              -keyalg RSA \
              -keysize 2048 \
              -validity 10000 \
              -alias upload \
              -storepass "$KEYSTORE_PASSWORD" \
              -keypass "$KEYSTORE_PASSWORD" \
              -dname "CN=Upload Key, O=Developer, C=US"
            cd "$CM_BUILD_DIR"
            git add android/upload.keystore
            git commit -m "chore: add Android upload keystore [skip ci]"
            git push origin HEAD
            echo "Upload keystore generated and committed to repo"
          fi
          echo "CM_KEYSTORE_PATH=$KEYSTORE_PATH" >> $CM_ENV
          echo "CM_KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD" >> $CM_ENV
          echo "CM_KEY_ALIAS=upload" >> $CM_ENV
          echo "CM_KEY_PASSWORD=$KEYSTORE_PASSWORD" >> $CM_ENV

      - name: Check Google Play readiness
        script: |
          echo "Checking Google Play setup status..."
          pip3 install PyJWT cryptography requests
          export SA_JSON="$CM_BUILD_DIR/$GOOGLE_SA_JSON_PATH"
          export PACKAGE_NAME="$PACKAGE_NAME"
          RESULT=$(python3 scripts/check_google_play.py)
          READY=$(echo "$RESULT" | python3 -c "import sys,json; print(str(json.load(sys.stdin)['ready']).lower())")
          if [ "$READY" != "true" ]; then
            echo "GOOGLE_PLAY_READY=false" >> $CM_ENV
            MISSING_STEPS=$(echo "$RESULT" | python3 -c "import sys,json; print('\n'.join(json.load(sys.stdin)['missing_steps']))")
            cat > $CM_BUILD_DIR/HOW_TO_GOOGLE_PLAY.md << GUIDE
          # Google Play Setup - Remaining Manual Steps

          Your Android AAB is in the build artifacts. Complete these steps, then push again:

          $MISSING_STEPS

          ## After completing all steps:
          Just \`git push\` again - Codemagic will publish automatically.
          GUIDE
            echo "Google Play not ready - see HOW_TO_GOOGLE_PLAY.md in artifacts"
          else
            echo "GOOGLE_PLAY_READY=true" >> $CM_ENV
            echo "Google Play ready for automated publishing"
          fi

      - name: Manage Android version
        script: |
          # Read iOS version for consistency (if iOS workflow ran)
          pip3 install PyJWT cryptography requests
          echo "APP_STORE_CONNECT_KEY_IDENTIFIER=$APPLE_KEY_ID" >> $CM_ENV
          echo "APP_STORE_CONNECT_ISSUER_ID=$APPLE_ISSUER_ID" >> $CM_ENV
          echo "APP_STORE_CONNECT_PRIVATE_KEY<<KEYDELIMITER" >> $CM_ENV
          cat "$CM_BUILD_DIR/$P8_KEY_PATH" >> $CM_ENV
          echo "" >> $CM_ENV
          echo "KEYDELIMITER" >> $CM_ENV
          VERSION_JSON=$(python3 scripts/manage_version_ios.py 2>/dev/null || echo '{"version":"1.0.0","version_id":"","state":"NEW"}')
          APP_VERSION=$(echo "$VERSION_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['version'])")
          echo "APP_VERSION=$APP_VERSION" >> $CM_ENV
          if [ "$GOOGLE_PLAY_READY" != "true" ]; then
            LATEST_BUILD=0
          else
            LATEST_BUILD=$(google-play get-latest-build-number \
              --package-name "$PACKAGE_NAME" \
              --tracks=production,beta,alpha,internal 2>/dev/null || echo "0")
          fi
          NEW_BUILD=$(($LATEST_BUILD + 1))
          if [ -z "$APP_VERSION" ] || [ "$APP_VERSION" = "" ]; then
            APP_VERSION="1.0.0"
          fi
          sed -i '' "s/^version:.*/version: ${APP_VERSION}+${NEW_BUILD}/" pubspec.yaml
          echo "ANDROID_VERSION_CODE=$NEW_BUILD" >> $CM_ENV
          echo "Android versionCode: $NEW_BUILD, versionName: $APP_VERSION"

      - name: Flutter packages
        script: flutter pub get

      - name: Build Android
        script: flutter build appbundle --release

      - name: Install Fastlane
        script: |
          cd android
          gem install bundler
          bundle install

      - name: Deploy to Google Play
        script: |
          if [ "$GOOGLE_PLAY_READY" != "true" ]; then
            echo "Skipping - Google Play setup incomplete"
            exit 0
          fi
          export GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_PATH="$CM_BUILD_DIR/$GOOGLE_SA_JSON_PATH"
          cd android
          bundle exec fastlane deploy_android

      - name: Sync subscriptions and IAP
        script: |
          if [ "$GOOGLE_PLAY_READY" != "true" ]; then
            echo "Skipping - Google Play setup incomplete"
            exit 0
          fi
          if ./scripts/check_changed.sh fastlane/iap_config.json; then
            export GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_PATH="$CM_BUILD_DIR/$GOOGLE_SA_JSON_PATH"
            cd android
            bundle exec fastlane sync_google_iap
          else
            echo "IAP config unchanged - skipping"
          fi

      - name: Update data safety form
        script: |
          if [ "$GOOGLE_PLAY_READY" != "true" ]; then
            echo "Skipping - Google Play setup incomplete"
            exit 0
          fi
          if ./scripts/check_changed.sh fastlane/data_safety.csv; then
            export GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_PATH="$CM_BUILD_DIR/$GOOGLE_SA_JSON_PATH"
            cd android
            bundle exec fastlane update_data_safety
          else
            echo "Data safety unchanged - skipping"
          fi

    artifacts:
      - build/app/outputs/**/*.aab
      - $CM_BUILD_DIR/HOW_TO_GOOGLE_PLAY.md
