name: Android Release
on:
  push:
    branches: [main]
  workflow_dispatch:

# Cancel in-progress runs when a newer build is triggered
concurrency:
  group: android-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  metadata:
    name: Upload Android Metadata
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Cache .ci-state
        uses: actions/cache@v4
        with:
          path: .ci-state
          key: ci-state-android-metadata-${{ hashFiles('fastlane/metadata/**', 'fastlane/screenshots/android/**') }}
          restore-keys: ci-state-android-metadata-

      - name: Install yq
        run: brew install yq

      - name: Init Summary
        run: echo "| Step | Status | Details |" >> $GITHUB_STEP_SUMMARY && echo "|------|--------|---------|" >> $GITHUB_STEP_SUMMARY

      - name: Link Fastlane
        run: scripts/ci/common/link-fastlane.sh android

      - name: Install Fastlane
        run: scripts/ci/common/install-fastlane.sh android

      - name: Check Google Play Readiness
        run: scripts/ci/android/check-readiness.sh

      - name: Upload Metadata & Screenshots
        id: upload-metadata
        run: scripts/ci/android/upload-metadata.sh

      - name: Sync IAP
        id: sync-iap
        run: scripts/ci/android/sync-iap.sh

      - name: Install Python dependencies
        run: pip3 install --break-system-packages google-api-python-client google-auth

      - name: Update Data Safety
        id: update-data-safety
        run: scripts/ci/android/update-data-safety.sh

      - name: Save .ci-state
        if: success()
        uses: actions/cache/save@v4
        with:
          path: .ci-state
          key: ci-state-android-metadata-${{ hashFiles('fastlane/metadata/**', 'fastlane/screenshots/android/**') }}

  build:
    name: Build & Upload Android
    needs: [metadata]
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install yq
        run: brew install yq

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('app/android/**/*.gradle*', 'app/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Link Fastlane
        run: scripts/ci/common/link-fastlane.sh android

      - name: Install Fastlane
        run: scripts/ci/common/install-fastlane.sh android

      - name: Setup Keystore
        run: scripts/ci/android/setup-keystore.sh

      - name: Install Python dependencies
        run: pip3 install --break-system-packages PyJWT google-api-python-client google-auth

      - name: Check Google Play Readiness
        run: scripts/ci/android/check-readiness.sh

      - name: Manage Version
        run: scripts/ci/android/manage-version.sh

      - name: Flutter Packages
        run: scripts/ci/common/flutter-setup.sh

      - name: Build AAB
        run: scripts/ci/android/build.sh

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: app/build/app/outputs/bundle/release/*.aab

      - name: Upload to Google Play
        run: scripts/ci/android/upload-binary.sh
