name: Trigger Codemagic Builds

on:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout config
        uses: actions/checkout@v4
        with:
          sparse-checkout: ci.config.yaml
          sparse-checkout-cone-mode: false

      - name: Install yq
        run: |
          if ! command -v yq &> /dev/null; then
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
          fi

      - name: Read Codemagic config
        id: config
        run: |
          if [ ! -f ci.config.yaml ]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            echo "ci.config.yaml not found - skipping trigger."
            exit 0
          fi

          APP_ID=$(yq -r '.codemagic.app_id // ""' ci.config.yaml)
          if [ -z "$APP_ID" ] || [ "$APP_ID" = "null" ]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            echo "app_id not configured - skipping trigger."
            exit 0
          fi

          echo "app_id=$APP_ID" >> "$GITHUB_OUTPUT"

          WORKFLOWS=$(yq -r '.codemagic.workflows[]' ci.config.yaml)
          DELIMITER="EOF_$(date +%s%N)"
          echo "workflows<<$DELIMITER" >> "$GITHUB_OUTPUT"
          echo "$WORKFLOWS" >> "$GITHUB_OUTPUT"
          echo "$DELIMITER" >> "$GITHUB_OUTPUT"

      - name: Trigger Codemagic builds
        if: steps.config.outputs.skip != 'true'
        env:
          CM_TOKEN: ${{ secrets.CM_API_TOKEN }}
          APP_ID: ${{ steps.config.outputs.app_id }}
          BRANCH: ${{ github.ref_name }}
        run: |
          echo "${{ steps.config.outputs.workflows }}" | while IFS= read -r workflow; do
            [ -z "$workflow" ] && continue
            if ! echo "$workflow" | grep -Eq '^[a-zA-Z0-9_-]+$'; then
              echo "ERROR: Invalid workflow name: $workflow"
              continue
            fi
            echo "Triggering: $workflow"
            curl --max-time 30 --retry 2 -sf -X POST https://api.codemagic.io/builds \
              -H "Content-Type: application/json" \
              -H "x-auth-token: $CM_TOKEN" \
              -d "{\"appId\": \"$APP_ID\", \"workflowId\": \"$workflow\", \"branch\": \"$BRANCH\"}" \
              && echo " -> success" \
              || echo " -> failed"
          done
