name: iOS Release
# POST-MIGRATION CLEANUP (after GitHub Actions workflows are verified in production):
#   - Remove .github/workflows/codemagic-trigger.yml
#   - Remove any Codemagic-specific configuration files
#   - Update README/docs to reference GitHub Actions instead of Codemagic
on:
  push:
    branches: [main]
  workflow_dispatch:

# Cancel in-progress runs when a newer build is triggered
concurrency:
  group: ios-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  metadata:
    name: Upload iOS Metadata
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Cache .ci-state
        uses: actions/cache@v4
        with:
          path: .ci-state
          key: ci-state-ios-metadata-${{ hashFiles('fastlane/metadata/**', 'fastlane/screenshots/ios/**') }}
          restore-keys: ci-state-ios-metadata-

      - name: Install yq
        run: brew install yq

      - name: Link Fastlane
        run: scripts/ci/common/link-fastlane.sh ios

      - name: Install Fastlane
        run: scripts/ci/common/install-fastlane.sh ios

      - name: Upload Metadata & Screenshots
        run: scripts/ci/ios/upload-metadata.sh

      - name: Sync IAP
        run: scripts/ci/ios/sync-iap.sh

      - name: Save .ci-state
        if: success()
        uses: actions/cache/save@v4
        with:
          path: .ci-state
          key: ci-state-ios-metadata-${{ hashFiles('fastlane/metadata/**', 'fastlane/screenshots/ios/**') }}

  build:
    name: Build & Upload iOS
    needs: [metadata]
    runs-on: macos-latest
    timeout-minutes: 60
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install yq
        run: brew install yq

      - name: Link Fastlane
        run: scripts/ci/common/link-fastlane.sh ios

      - name: Install Fastlane
        run: scripts/ci/common/install-fastlane.sh ios

      - name: Setup Signing (Match)
        run: scripts/ci/ios/setup-signing.sh

      - name: Install Python dependencies
        run: pip3 install --break-system-packages PyJWT

      - name: Manage Version
        run: scripts/ci/ios/manage-version.sh

      - name: Set Build Number
        run: scripts/ci/ios/set-build-number.sh

      - name: Flutter Packages
        run: scripts/ci/common/flutter-setup.sh

      - name: Build IPA
        run: scripts/ci/ios/build.sh

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: app/build/ios/ipa/*.ipa

      - name: Upload to App Store
        run: scripts/ci/ios/upload-binary.sh
